### ISSUE TITLE
Assistance needed to understand these tests.

### ISSUE THREAD

**Issue by lukebakken** [devfaz/rabbitmq_debug#1]
Please see my comment here:

https://groups.google.com/d/msg/rabbitmq-users/eC8jc-YEt8s/GFAln7h1AQAJ

How would you like to continue discussion?

**Comment by devfaz** [comment]
"In testing I do see that the various scripts to report on broken queues do return queues. However, if I disable the step that stops a node, I still see some queues reported as "broken". But, they appear normal in the management interface and I can publish to them."

well, it depends.

The script checks different things.

"broken bindings" are checked by sending a msg to every known routing-key to every exchange.

"broken queues" checks if there are queues which do not have a "valid" msg-count (f.e. NaN), this also happens (for a short period of time) during "normal operating". So while the the load-generator is running, the check will always show some queues, but these queues should change at every run.

**Comment by lukebakken** [comment]
I will modify my process to re-try if `NaN` is seen. I need it to be reliable in the case where no node is restarted, so that I am certain there are issues when one of them is restarted.
