### ISSUE TITLE
"alternate-exchange" is not configured

### ISSUE THREAD

**Issue by lukebakken** [devfaz/rabbitmq_debug#2]
https://github.com/devfaz/rabbitmq_debug#check_rabbitmq_unroutable_msg

> change your policy to configure an "alternate exchange" => "unroutable"

The scripts never specify an alternate exchange. Should this be part of the `ha` policy?

**Comment by devfaz** [comment]
Yes, the scripts are used to detect both issues.. "unroutable msgs" AND "broken queues". If you would like to detect unroutable msgs you have to enhance your ha-policy to define the exchange. 

But I think your right - we could do this by default.
